id: I4453CE56
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T14:20:48+00:00'
last_modified: '2022-06-08T03:41:03.825356+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3714
  title: མི་ལ་རས་པའི་རྣམ་ཐར་དང་གསོལ་འདེབས་དང་མགུར་འབུམ་སོགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    C592:
      image_group_id: I1KG3803
      title: ''
      total_pages: 1042
      order: 1
      base_file: C592.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
