id: P005522
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3714
  title: མི་ལ་རས་པའི་རྣམ་ཐར་དང་གསོལ་འདེབས་དང་མགུར་འབུམ་སོགས།
  author: ''
  volumes:
    8d2eacf3ef314feda688e7040a676307:
      image_group_id: I1KG3803
      title: ''
      volume_number: 1
      total_pages: 1042
