id: P005522
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 11:56:14.144811
source_metadata:
  id: bdr:W1KG3714
  title: མི་ལ་རས་པའི་རྣམ་ཐར་དང་གསོལ་འདེབས་དང་མགུར་འབུམ་སོགས།
  author: ''
  volumes:
    8d2eacf3ef314feda688e7040a676307:
      image_group_id: I1KG3803
      title: ''
      volume_number: 1
      total_pages: 1042
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
